#include <stdio.h>

/*	Each new term in the Fibonacci sequence is generated by adding the previous 
	two terms. By starting with 1 and 2, the first 10 terms will be:

		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not 
	exceed four million, find the sum of the even-valued terms.
*/

/*	See theory below	*/
int main(int argc, char *argv[])
{
	long f3=2, f6=0, sum = 0, f=2;

	while (f < 4000000) {
		sum += f;
		//	Update numbers
		f = 4*f3 + f6;
		f6 = f3;
		f3 = f;
	}

	printf("Sum: %ld\n", sum);
	return 0;
}

/*	We want to find only every third Fibonacci number, so we want to express
	Fn in terms of Fn-3 and Fn-6:

	Fn	= Fn-1 					+ Fn-2
		= Fn-2 			+ Fn-3 	+ Fn-3	+ Fn-4
		= Fn-3 + Fn-4 	+ Fn-3	+ Fn-3	+ Fn-5 + Fn-6 	(now group terms)
		= 3*Fn-3 + (Fn-4 + Fn-5) + Fn-6					(Fn-4 + Fn-5 = Fn-3)
	Fn	= 4*Fn-3 + Fn-6
*/