#include <stdio.h>

/*	Each new term in the Fibonacci sequence is generated by adding the previous 
	two terms. By starting with 1 and 2, the first 10 terms will be:

		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not 
	exceed four million, find the sum of the even-valued terms.
*/

int main(int argc, char *argv[])
{
	long int first = 1, second = 2, sum = 0, tmp = 0;

	while (second < 4000000) {
		// Every third number will be even, so we only need to find every third
		// number and add them all together

		sum += second;

		// now generate third number, example is for first iteration
		first = first + second;		//first = 3, second = 2
		second = first + second;	//first = 3, second = 5
		tmp = second;				//tmp = 5
		second = first + second;	//first = 3, second = 8
		first = tmp;				//first = 5, second = 8

	}

	printf("Sum: %ld\n", sum);
	return 0;
}